name: addonnextupdate
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'denylist'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Thanks for your support, domain(s) has been added to the denylist and will be added in the next update. The update takes place at least every 24 hours. Updated list versions are usually available from 04:00 UTC at the latest.
